name: Global build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

env:
  REGISTRY: "ghcr.io"
  NAMESPACE: "this-is-tobi/mirror"
  MULTI_ARCH: true
  USE_QEMU: true

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ env.REGISTRY }}
      NAMESPACE: ${{ env.NAMESPACE }}
      MULTI_ARCH: ${{ env.MULTI_ARCH }}
      USE_QEMU: ${{ env.USE_QEMU }}
    steps:
      - name: Exposing env vars
        run: echo "Exposing env vars"

  mattermost:
    uses: ./.github/workflows/mattermost.yml
    needs:
      - expose-vars
    permissions:
      contents: read
      packages: write
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      MULTI_ARCH: ${{ needs.expose-vars.outputs.MULTI_ARCH == 'true' }}
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}

  outline:
    uses: ./.github/workflows/outline.yml
    needs:
      - expose-vars
    permissions:
      contents: read
      packages: write
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      MULTI_ARCH: ${{ needs.expose-vars.outputs.MULTI_ARCH == 'true' }}
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}
